### PR TITLE
add title alias, bump dependencies

### PR DESCRIPTION
**Pull request by Zh40Le1ZOOB**

### CODE REVIEW

**Review by Cryolitia — APPROVED** [review]

**Comment by Zh40Le1ZOOB** [comment]
@Cryolitia WAIT! This should not be squash and merge! Commit message will lost type and semantic-release will not work!

**Comment by Zh40Le1ZOOB** [comment]
……whatever, seems semantic-release just ignored unconventional commit message, but this is not expected for our workflow……

**Comment by Zh40Le1ZOOB** [comment]
@Cryolitia what to do next?

**Comment by Cryolitia** [comment]
@Zh40Le1ZOOB 分支已重置，开新pr。

强制要求所有PR标题必须语义化，必要情况下使用CI检查

**Comment by Zh40Le1ZOOB** [comment]
> @Zh40Le1ZOOB 分支已重置，开新pr。
> 
> 强制要求所有PR标题必须语义化，必要情况下使用CI检查

OK，这部分我加到贡献指南里

**Pull request merged**
